openapi: 3.0.0
info:
  version: '1.0'
  title: "MyKiko OpenAPI 3.0"
  description: API for managing pets.
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api/v1
    description: Localhost
paths:
  /authentications:
    post:
      description: >-
        Verify the user's credentials in the system
      summary: Authenticates the user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email: 
                  type: String
                  description: 'Email address of the user'
                password:
                  type: String
                  description: 'Personal password of the user'
      responses:
        '200':
          description: 'User verified'
          headers:
            'Location':
              schema:
                type: string
              description: Link to the user plus his informations
      
  /registration:
    post:
      description: >-
        Creates a new user in the system
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email: 
                  type: String
                  description: 'Email address of the new user'
                password:
                  type: String
                  description: 'Personal password of the new user'
      responses:
        '201':
          description: 'User created. Link in the Location header'
          headers:
            'Location':
              schema:
                type: string
              description: Link to the newly created user
        '400':
          description: 'Input fields are empty'
          headers:
            'Message':
              schema:
                type: string
              description: Registration failed. input empty

  /infoAnimale:
    get:
      description: >-
        Gets the pet's info from the database
      summary: Sees all the info
      responses:
        '200':
          description: 'Collections of pets'
          content:
            application/json:
              schema:
                type: string
                items:
                  $ref: '#/components/schemas/InfoAnimale'
  
  /modificaCredenziali:
    put:
      description: >-
        Modifies user's credentials
      summary: Changes user's info
      responses:
          '200':
            description: 'Changes applyed'
            schema:
              type: array
              items:
                $ref: '#/definitions/schemas'
            examples:
              application/json:
                - emailNew: newemail@gmail.com
                  password: newpassword123
          '400':
            description: 'Empty inputs fields'
            headers:
              'Message':
                schema:
                  type: string
                description: Failed changes, empty inputs fields

  /modificaInfoAnimale:
    put:
      description: >-
        Modifies pet's data
      summary: Changes pet's info
      responses:
        '200':
          description: 'Changes applyed'
           schema:
              type: array
              items:
                $ref: '#/definitions/schemas'
        '400':
           description: 'Empty inputs fields'
            headers:
              'Message':
                schema:
                  type: string
                description: Failed changes, empty inputs fields
                
  /AggiungiAnimale:
    post:
      description: >-
        Puoi aggiungere il tuo animale inserendo le informazioni disponibili
      summary: Crea un nuovo animale nel database
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/schemas'
      responses:
        201:
          description: 'Data inserted'
          schema:
            $ref: '#/definitions/schemas'
          examples:
            application/json:
              - email: emailUtente
                nome: nome_animale
                razza: razza_animale
                eta: eta_animale
                peso: peso_animale
                codicechip: codicechip_animale
        400:
          description: Empty imputs
          examples:
            application/json:
              - email: emailUtente
                nome: 
                razza: 
                eta: 
                peso: 
                codicechip:
  
components:
  schemas:
    Animale:
      type: object
      required:
        - email
        - nome
        - razza
        - eta
        - peso
        - CodiceChip
        - caratteristicaSpecie
      properties:
        email:
          type: String
          description: 'User email'
        nome:
          type: String
          description: 'Nome animale'
        razza:
          type: String
          description: 'Razza animale'
        eta:
          type: Number
          description: 'Eta animale'
        peso:
          type: Number
          description: 'Peso animale'
        codiceChip:
          type: String
          description: 'Codice del chip identificativo'
        caratteristicaSpecie:
          type: String
          description: descrizione caratteristica specie
         
    User:
      type: object
      required:
        - email
        - password
        - animale
      properties:
        email:
          type: string
          description: 'User email'
        password:
          type: string
          description: 'User password'
        animale:
          type: object
          desrciption: 'array dati animale'
